// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quran.Repository;

namespace Quran.Repository.Migrations
{
    [DbContext(typeof(QuranDBContext))]
    [Migration("20210827202137_2nd Migrton")]
    partial class _2ndMigrton
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quran.Entity.AudioRecitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AyathId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuariId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AudioRecitations");
                });

            modelBuilder.Entity("Quran.Entity.Ayath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AyathDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AyathId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AyathNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BangDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurahId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ayaths");
                });

            modelBuilder.Entity("Quran.Entity.Quari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuariId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quaris");
                });

            modelBuilder.Entity("Quran.Entity.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanglaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevelationPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurahId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurahName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Surahs");
                });
#pragma warning restore 612, 618
        }
    }
}
